// <auto-generated />
namespace WebShop2018.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Validacije : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Validacije));
        
        string IMigrationMetadata.Id
        {
            get { return "201805071711034_Validacije"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
