// <auto-generated />
namespace WebShop2018.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _1toN : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1toN));
        
        string IMigrationMetadata.Id
        {
            get { return "201806151901477_1toN"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
